version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080" # maps the container port 8080 to the host port 8080
    environment:
      SPRING_PROFILES_ACTIVE: docker # Docker profile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge